### ISSUE TITLE
Installed the fix but still sending out duplicate email. [Ref:fix #14: Do not sent duplicates]

### ISSUE THREAD

**Issue by gumshooe** [reneeb/otrs-MultiSMTP#15]
Hi OP,

Thanks for this package.
I installed this fix for my OTRS6 on Centos 7. [Ref:fix #14: Do not sent duplicates]
But my OTRS6 still sending out duplicate emails for a notification.

I'm a noob. But is is it something to do with the fallback module?

 my $UseFallback = $ConfigObject->Get('MultiSMTP::UseFallback') || 1;
    if($UseFallback){
        # use standard SMTP module as fallback
        my $Module  = $ConfigObject->Get('MultiSMTP::Fallback');

I am only using one smtp setting.

Best regards,
WNMRJD

**Comment by reneeb** [comment]
Did you restart the daemon?

**Comment by Axcendio** [comment]
Hi Reneeb,
Yupe, we did.

Right now it's not sending out duplicate notification anymore.

![image](https://user-images.githubusercontent.com/33312438/39106326-8e5c4ce6-46ed-11e8-99ca-4ed9371074de.png)
