### ISSUE TITLE
http 500 error

### ISSUE THREAD

**Issue by NeverMin** [reneeb/otrs-MultiSMTP#3]
[Fri Mar 06 00:02:36.126942 2015] [perl:error] [pid 1135] [client 222.92.186.110:35449] Use of each() on hash after insertion without resetting hash iterator results in undefined behavior, Perl interpreter: 0x7f75ded85120 at /opt/otrs/Kernel/cpan-lib/Apache2/Reload.pm line 171.\n, referer: https://otrsserver/otrs/index.pl?Action=AgentTicketZoom;TicketID=43;ArticleID=113

**Comment by NeverMin** [comment]
@reneeb 
Ubuntu 14.04.1 64bit, Apache 2.4.7
OTRS 4.0.6

o Apache2::Reload..................ok (v0.12)
  o Archive::Tar.....................ok (v1.90)
  o Archive::Zip.....................ok (v1.30)
  o Crypt::Eksblowfish::Bcrypt.......ok (v0.009)
  o Crypt::SSLeay....................ok (v0.58)
  o Date::Format.....................ok (v2.24)
  o DBI..............................ok (v1.630)
  o DBD::mysql.......................ok (v4.025)
  o DBD::ODBC........................Not installed! (optional  - Required to connect to a MS-SQL database.)
  o DBD::Oracle......................Not installed! (optional  - Required to connect to a Oracle database.)
  o DBD::Pg..........................Not installed! (optional  - Required to connect to a PostgreSQL database.)
  o Encode::HanExtra.................ok (v0.23)
  o GD...............................ok (v2.46)
    o GD::Text.......................ok (v0.86)
    o GD::Graph......................ok (v1.44)
  o IO::Socket::SSL..................ok (v1.965)
  o JSON::XS.........................ok (v2.34)
  o List::Util::XS...................ok (v1.27)
  o LWP::UserAgent...................ok (v6.06)
  o Mail::IMAPClient.................ok (v3.35)
    o IO::Socket::SSL................ok (v1.965)
  o ModPerl::Util....................ok (v2.000008)
  o Net::DNS.........................ok (v0.68)
  o Net::LDAP........................ok (v0.58)
  o PDF::API2........................ok (v2.020)
  o Template.........................ok (v2.24)
  o Template::Stash::XS..............ok (undef)
  o Text::CSV_XS.....................ok (v1.02)
  o Time::HiRes......................ok (v1.9725)
  o Time::Piece......................ok (v1.20_01)
  o XML::Parser......................ok (v2.41)
  o YAML::XS.........................ok (v0.41)

Bundled modules:
  o Algorithm::Diff..................ok (v1.1902)
  o Apache::DBI......................ok (v1.12)
  o Authen::SASL.....................ok (v2.16)
  o CGI..............................ok (v4.03)
  o CSS::Minifier....................ok (v0.01)
  o Class::Inspector.................ok (v1.28)
  o Crypt::PasswdMD5.................ok (v1.40)
  o Date::Pcalc......................ok (v1.2)
  o Email::Valid.....................ok (v1.194)
  o Encode::Locale...................ok (v1.03)
  o IO::Interactive..................ok (v0.0.6)
  o JSON.............................ok (v2.90)
  o JSON::PP.........................ok (v2.27203)
  o JavaScript::Minifier.............ok (v1.11)
  o LWP..............................ok (v6.08)
  o Linux::Distribution..............ok (v0.21)
  o Locale::Codes....................ok (v3.31)
  o MIME::Tools......................ok (v5.505)
  o Mail::Address....................ok (v2.13)
  o Mail::Internet...................ok (v2.13)
  o Module::Refresh..................ok (v0.17)
  o Mozilla::CA......................ok (v20130114)
  o Net::HTTP........................ok (v6.07)
  o Net::IMAP::Simple................ok (v1.2205)
  o Net::SSLGlue.....................ok (v1.053)
  o Proc::Daemon.....................ok (v0.14)
  o SOAP::Lite.......................ok (v1.11)
  o Sys::Hostname::Long..............ok (v1.4)
  o Text::CSV........................ok (v1.32)
  o Text::Diff.......................ok (v1.41)
  o URI..............................ok (v1.64)
  o YAML.............................ok (v1.09)
  o parent...........................ok (v0.228)

**Comment by reneeb** [comment]
Do you have other addons installed as well? I do not use "each" in this module... Can you do a ```grep -r "each %"``` at <OTRS_HOME>?

**Comment by NeverMin** [comment]
Yes, I has many addons, I did not find any use each() in my system (*.pm),
but, I will test clear OTRS system again and let you know any upate. Thank
you.

2015-03-11 17:42 GMT+08:00 Renee <notifications@github.com>:

**Comment by NeverMin** [comment]
On a clean system testing, work well. using OTRS Appliance v4.0.6, thank  you to @reneeb
