### ISSUE TITLE
Problems with auto responses

### ISSUE THREAD

**Issue by reneeb** [reneeb/otrs-MultiSMTP#5]
From a comment on OPAR:

I have re-configure my OTRS to send to many SMTP server, however what about auto response? seems not read MultiSMTP setting ? have an error in the log Can't send message: 550Start mail input; end with <CRLF>.<CRLF>

**Comment by padrogass** [comment]
hi reneeb!

is there any solution with auto-responses?

Thank you for the package!

**Comment by reneeb** [comment]
There was a bug with regard to auto-responses. This should be fixed in the latest version.
