### ISSUE TITLE
MultiSMTP not working after upgrading for 4.0.? to 5.0.14

### ISSUE THREAD

**Issue by choclin** [reneeb/otrs-MultiSMTP#9]
Hi,
I upgraded my OTRS instance from an early 4.0 (around 4.0.5, I think) to the current 5.0.14. I also reinstalled the MultiSMTP package, but I always get errors when I try to send an email:

```
Backend ERROR: OTRS-CGI-57 Perl: 5.14.2 OS: linux Time: Fri Nov 25 00:18:12 2016

 Message: Impossible to send message to: my@address.email .

 RemoteAddress: 192.168.158.51
 RequestURI: /otrs/index.pl

 Traceback (12316): 
   Module: Kernel::System::Ticket::Article::ArticleSend Line: 2255
   Module: Kernel::Modules::AgentTicketCompose::Run Line: 843
   Module: Kernel::System::Web::InterfaceAgent::Run Line: 1053
   Module: ModPerl::ROOT::ModPerl::Registry::opt_otrs_bin_cgi_2dbin_index_2epl::handler Line: 40
   Module: (eval) (v1.99) Line: 204
   Module: ModPerl::RegistryCooker::run (v1.99) Line: 204
   Module: ModPerl::RegistryCooker::default_handler (v1.99) Line: 170
   Module: ModPerl::Registry::handler (v1.99) Line: 31
```

What should I do to make it work again?

**Comment by reneeb** [comment]
First of all, please enable the debugging mode (SysConfig option MultiSMTP::Debug) and decrease the log level (Framework -> Core::Log -> set to 'debug'). Then try to send an email and check the logs.

I'll release a new version in a few hours that enables Net::SMTP debug automatically when debugging is enabled. If the current debugging doesn't show enough information, this could help as well.

Kind regards,
Renée

**Comment by choclin** [comment]
Hi Renée,

thanks for your quick answer, I already enabled the the MultiSMTP::Debug mode and now decreased the minimum log level to debug. The details show directly in the browser do not show more information now. Should I look into a log file on the disk?

Thanks
Dominic

**Comment by reneeb** [comment]
Hi Dominic,

yes, you should look into the log file - adding debugging output to the browser would be bad practice as this would lead to information leaks...

If you use syslog for logging, you have to look at /var/log/syslog or /var/log/messages (depending on the operating system). If you use a separate file for OTRS logging, please look into that file.

Kind regards,
Renee

**Comment by choclin** [comment]
Okay, I found this message in /var/log/syslog:

```
Nov 25 07:20:18 otrs5 OTRS-otrs.Console.pl-Maint::PostMaster::MailAccountFetch-57[3146]: [Error][Kernel::System::Email::MultiSMTP::SMTP::Send][Line:142]: SMTP authentication failed: 500Need MIME::Base64 and Authen::SASL todo auth! Enable Net::SMTP debug for more info!
Nov 25 07:20:18 otrs5 OTRS-otrs.Console.pl-Maint::PostMaster::MailAccountFetch-57[3146]: [Info][Kernel::System::Email::Send] Error sending message
```

MIME::Base64 was already installed, but Authen::SASL not. After installing it, sending mails worked. I'm only wondering why it worked before because I didn't change the credentials and auth methods for SMTP.
